### ISSUE TITLE
Introduce Eslint Test

### ISSUE THREAD

**Issue by ryuseikurata** [KimuraYu45z/angular-firebase-schematics#2]
should test exported typescript file about whether eslint validates or not.

After using this schematics, there where many errors in my repositoy. 

for example, below the code, there is an error that static member should be higher than method.
```
class Entity {
 constructor() {}
 validate(){}
 static member: string
}
```

**Comment by KimuraYu45z** [comment]
ESLint rules will variate among users so I can't support a specifit ESLint rule.
So please run `eslint xxx --fix` command after generating files with this schematics.
